9-Three-Pages
Apleeeee/TopBody pull request #12
Opened 2024-01-18 20:28 UTC by Apleeeee

Грубая вёрстка начальных страниц

2024-01-18 20:31 UTC, chikibrikie approved these changes
LGTM!

2024-01-19 14:35 UTC, Bibazavr requested changes
Надо бы добавить стилей, чтобы приложение выглядело +- как в дизайне

2024-01-20 06:10 UTC, Bibazavr requested changes
Мини исправления надо сделать

2024-01-20 06:10 UTC, Bibazavr commented on src/pages/Auth/ui/ForgotPasswordScreen.tsx
> +import { TextInput } from "react-native-paper";
Импорт не из `shared/ui`

2024-01-20 06:10 UTC, Bibazavr commented on src/pages/Auth/ui/SignInScreen.tsx
> +import { TextInput } from "react-native-paper";
Импорт не из `shared/ui`

2024-01-20 06:10 UTC, Bibazavr commented on src/pages/Auth/ui/ForgotPasswordScreen.tsx
> +    backgroundColor: "#FFFBFF",
backgroundColor лучше брать из темы [тут](https://callstack.github.io/react-native-paper/docs/guides/theming#accessing-theme-properties) есть пример или в мр Ромы

2024-01-20 06:10 UTC, Bibazavr commented on src/pages/Auth/ui/SignInScreen.tsx
> +    backgroundColor: "#FFFBFF",
и туть

2024-01-20 06:10 UTC, Bibazavr commented on src/pages/Auth/ui/SignInScreen.tsx
> +  buttonAndText: {},
Стиль ничего не делает - удалить

2024-01-20 06:10 UTC, Bibazavr commented on src/pages/Auth/ui/SignUpScreen.tsx
> +import { TextInput, Checkbox } from "react-native-paper";
обертка

2024-01-21 10:08 UTC, Bibazavr approved these changes
LGTM!

2024-01-21 19:32 UTC, merged